name: "Use goliothctl"
description: "Use the Golioth CLI (goliothctl) from your GitHub Actions"
branding:
  icon: "cpu"
  color: "green"

inputs:
  apiKey:
    description: "The API Key generated via goliothctl or web console"
    required: true
  projectId:
    description: "Project ID to use."
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./actions/create-device
      with:
        apiKey: ${{ inpus.apiKey }}
        projectId: ${{ inputs.projectId }}