name: "Use goliothctl"
description: "Use the Golioth CLI (goliothctl) from your GitHub Actions"
branding:
  icon: "cpu"
  color: "green"

inputs:
  apiKey:
    description: "The API Key generated via goliothctl or web console"
    required: true
  projectId:
    description: "Project ID to use."
    required: true
  deviceName:
    description: "Device name."
    required: false
  psk:
    description: "Pre-shared key. Used as part of device authentication."
    required: false
  pskId:
    description: "Pre-shared key ID. Used as part of device authentication."
    required: false
  deviceTag:
    description: "Tag used to target a release."
    required: false
  file:
    description: "File to use for artifact."
    required: false
  artifactVersion:
    description: "Artifact semantic version."
    required: false

runs:
  using: "composite"
  steps:
    - uses: ./actions/setup-goliothctl
      with:
        apiKey: ${{ inputs.apiKey }}
        projectId: ${{ inputs.projectId }}

    - if: ${{ inputs.deviceName != '' }}
      uses: ./actions/create-device
      with:
        deviceName: ${{ inputs.deviceName }}
        psk: ${{ inputs.psk }}
        pskId: ${{ inputs.pskId }}
        deviceTag: ${{ inputs.deviceTag }}

    - if: ${{ inputs.file != '' }}
      uses: ./actions/create-artifact
      with:
        file: ${{ inputs.file }}
        version: ${{ inputs.artifactVersion }}