name: Test all actions

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download file for Artifact
        id: dl-artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'golioth/thingy91-golioth'
          file: 'app_update_thingy91_v1.0.0.bin'

      - name: Create random device name
        uses: TGPSKI/name-generator-node-action@v2
        id: generator
        with:
          separator: '_'
          length: '3'
          style: 'lowerCase'
          
      - name: Use goliothctl
        uses: ./
        with:
          apiKey: ${{ secrets.APIKEY }}
          projectId: ${{ vars.PROJECTID }}
          deviceName: ${{ steps.generator.outputs.name }}
          deviceTag: ci

    #   - name: Create Artifact
    #     uses: goliothlabs/create-artifact@main
    #     with:
    #       file: app_update_thingy91_v1.0.0.bin
    #       version: 1.0.0

    #   - name: Create Release
    #     uses: goliothlabs/create-release@main
    #     with:
    #       artifact: main
    #       version: 1.0.0
    #       deviceTag: ci
          
    #   - name: List devices
    #     run: goliothctl device list