name: Test all actions

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download file for Artifact
        id: dl-artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'golioth/thingy91-golioth'
          file: 'app_update_thingy91_v1.0.0.bin'

      - name: Create random device name
        uses: tjcorr/gha-unique-name-generator@v1
        id: generator
        with:
          separator: '-'
          prefix: 'ci'
          
      - name: Use goliothctl
        uses: ./
        with:
          apiKey: ${{ secrets.APIKEY }}
          projectId: ${{ vars.PROJECTID }}
          deviceName: ${{ steps.generator.outputs.name }}
          deviceTag: ci
          file: app_update_thingy91_v1.0.0.bin
          artifactVersion: 1.0.0
          releaseArtifact: main
          releaseVersion: 1.0.0
          releaseTag: ci
          
      - name: List devices
        run: goliothctl device list